---
title: "My First Markdown"
author: "Esad"
date: "7/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Download sleep study data
```{r}
library (readr)
sleep<-read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv", col_types=cols(
  id = col_double(),
   Reaction = col_double(),
  Days = col_double(),
  Subject = col_double()  
))
head(sleep)
```

```{r}
library (ggplot2)
ggplot(sleep, aes(x=Days, y=Reaction)) + 
  geom_point() + 
  geom_smooth() + 
  scale_x_continuous(breaks=seq(0, 8, by = 2)) + 
  facet_wrap(~Subject)
```

Summary statistics

```{r}
library (dplyr)
sleep %>%
  group_by(Subject) %>%
  summarise(mean(Reaction))
```


Mean-center reaction times and plot on a single axis
```{r}
sleep %>% 
  group_by(Subject) %>% 
  mutate(mean_centered_reaction=Reaction-mean(Reaction)) %>% 
  ggplot(aes(x=Days, y=mean_centered_reaction, colour=factor(Subject))) +
  geom_smooth(show.legend = FALSE, se=FALSE)+
  scale_x_continuous(breaks = seq(0, 8, by=2))
```